# hugo.toml

baseURL = 'https://www.chenyunsi.com/'
languageCode = 'zh-cn'
title = '欢迎来到小石榴的世界'
theme = 'PaperMod'

# PaperMod 主题的特定配置
[params]
  description = "记录小石榴成长的珍贵瞬间"
  author = "小石榴的爸爸妈妈"
  js = [
    "https://cdn.jsdelivr.net/npm/chart.js",
    "/js/growth-chart.js"
  ]

# 菜单配置，这里定义网站右上角的导航栏
[[menu.main]]
  identifier = 'baby'
  name = '关于宝宝'
  url = 'https://www.chenyunsi.com/baby/'
  weight = 1

[[menu.main]]
  identifier = 'dad'
  name = '关于爸爸'
  url = 'https://www.chenyunsi.com/dad/'
  weight = 2

[[menu.main]]
  identifier = 'mom'
  name = '关于妈妈'
  url = 'https://www.chenyunsi.com/mom/'
  weight = 3


# 启用相关功能
[markup.goldmark.renderer]
  unsafe = true
